name = "siren"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true

# Routes (v3 style)
[[routes]]
pattern = "zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "ava.game.naver.com.zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "quiz.int.vidio.com.zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "graph.instagram.com.zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "help.viu.com.zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "support.zoom.us.zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "cache.netflix.com.zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "graph.facebook.com.zerostore.tech/*"
zone_name = "zerostore.tech"

[[routes]]
pattern = "dogseechew.com.zerostore.tech/*"
zone_name = "zerostore.tech"

# KV binding
[[kv_namespaces]]
binding = "SIREN"
id = "d060c65ff1734a2eb44a03571320ece5"

# Build (Rust worker / workers-rs)
[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

# Vars
[vars]
UUID = "1abe4bd9-06f0-4fb7-9173-d4524b056a3a"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/link.html"
CONVERTER_PAGE_URL = "https://raw.githubusercontent.com/dit1304/Cloud/main/web/converter.html"
