name: cf workers
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install Wrangler
        run: npm install -g wrangler@4
        
      # 预先构建，设置正确的环境变量
      - name: Build Worker with bulk memory support
        run: |
          cargo install -q worker-build
          worker-build --release
        env:
          RUSTFLAGS: "-C target-feature=+bulk-memory"
          
      - name: Deploy to Cloudflare Workers
        run: npx wrangler deploy --no-bundle
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
