name: cf workers

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4

      # Toolchain Rust (wajib karena build via cargo)
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # Wrangler v4
      - name: Install Wrangler
        run: npm install -g wrangler@4

      # (Opsional) Pastikan binaryen terbaru tersedia
      - name: Install binaryen (optional)
        run: sudo apt-get update && sudo apt-get install -y binaryen

      # Deploy (prod/top-level env) + enable bulk-memory untuk wasm-opt
      - name: Deploy to Cloudflare Workers (prod)
        run: npx wrangler deploy --env=""
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          #WASMOPT_ARGS: --enable-bulk-memory
