name: cf workers

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cf
    steps:
      - uses: actions/checkout@v4

      # 安装 Rust 工具链
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      # 安装 Wrangler v4
      - name: Install Wrangler
        run: npm install -g wrangler@4

      # 安装最新 Binaryen（包含新版 wasm-opt）
      - name: Install binaryen (latest)
        run: |
          wget https://github.com/WebAssembly/binaryen/releases/download/version_116/binaryen-version_116-x86_64-linux.tar.gz
          tar -xzf binaryen-version_116-x86_64-linux.tar.gz
          sudo mv binaryen-version_116 /usr/local/binaryen
          echo "/usr/local/binaryen/bin" >> $GITHUB_PATH

      # 部署到 Cloudflare Workers
      - name: Deploy to Cloudflare Workers (prod)
        run: npx wrangler deploy --env=""
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          WASMOPT_ARGS: --enable-bulk-memory
